services:
  server:
    build:
      context: .
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/my_database
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=D9d9_Bogdan
    networks:
      - testos-teron
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: D9d9_Bogdan
      POSTGRES_DB: my_database
    volumes:
      - postgres_data:/var/lib/postgresql@16/data
      - ./init:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    networks:
      - testos-teron
volumes:
  postgres_data:

networks:
  testos-teron:
    driver: bridge